-- ============================================================================
-- BetterAuth tables (generated by @better-auth/cli)
-- ============================================================================

create table "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" boolean not null,
  "image" text,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz default current_timestamp not null
);

create table "session" (
  "id" text not null primary key,
  "expiresAt" timestamptz not null,
  "token" text not null unique,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz not null
);

create table "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz default current_timestamp not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- ============================================================================
-- App tables
-- ============================================================================
-- Note: user-reference columns are `text` (not `uuid`) because BetterAuth
-- generates string IDs (cuid/nanoid format), not UUIDs. The RLS helper
-- function in 0002_rls.sql returns text accordingly.
-- No FKs to "user" table — BetterAuth identities are referenced opaquely
-- per the design spec's "trust the JWT" decision.

create table channels (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  type        text not null check (type in ('public', 'private')),
  created_by  text not null,
  created_at  timestamptz not null default now()
);

create table channel_members (
  channel_id    uuid not null references channels(id) on delete cascade,
  user_id       text not null,
  role          text not null default 'member' check (role in ('owner', 'member')),
  joined_at     timestamptz not null default now(),
  last_read_at  timestamptz not null default now(),
  primary key (channel_id, user_id)
);

create table messages (
  id                  uuid primary key default gen_random_uuid(),
  channel_id          uuid not null references channels(id) on delete cascade,
  author_kind         text not null check (author_kind in ('user', 'ai')),
  author_id           text,
  invoked_by_user_id  text,
  body                text not null default '',
  client_id           uuid,
  ai_status           text check (ai_status in ('streaming', 'complete', 'error')),
  created_at          timestamptz not null default now(),
  constraint messages_ai_status_consistency
    check ((author_kind = 'ai') = (ai_status is not null))
);

create index messages_channel_created_idx
  on messages (channel_id, created_at desc, id desc);

create unique index messages_client_id_unique
  on messages (channel_id, author_id, client_id)
  where client_id is not null;
